Railsでテストを書く
isshi-hasegawa/fjord-books_app pull request #7
Opened 2022-02-04 23:33 UTC by isshi-hasegawa

2022-02-10 06:55 UTC, u1tnk requested changes

2022-02-10 06:55 UTC, u1tnk commented on test/fixtures/relationships.yml
> +#one:
コメントアウトしたものは消しましょう。
gitがあれば戻すことは簡単なので。

2022-02-10 06:55 UTC, u1tnk commented on test/system/report_test.rb
> +    click_on '戻る'
setupで毎回ログインするので戻る必要は無いす。

2022-02-10 06:55 UTC, u1tnk commented on test/system/report_test.rb
> +    click_button 'ログイン'
ログインしない状態のテストも普通は必要になりますし、こう書くとログイン自体のテストが無いので、分けた方が良いですね。
ログインのように頻出なテストコードはメソッド化して、必要なテストで呼ぶようにしましょう。

2022-02-10 20:47 UTC, isshi-hasegawa commented on test/system/report_test.rb
> +    click_button 'ログイン'
ありがとうございます！
切り出したログインのメソッドはシステムテスト間で再利用するものと考え、ApplicationSystemTestCaseクラスに定義することにしました。

2022-02-11 00:56 UTC, u1tnk approved these changes

2022-02-11 01:20 UTC, merged